---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edukurs-db-ceph
  namespace: edukurs
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
  instances: 1
  storage:
    storageClass: ceph-block
    size: 10Gi
  bootstrap:
    initdb:
      database: mydatabase
      owner: myuser
      secret:
        name: edukurs-db-ceph-secret
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/edukurs-db-ceph"
      endpointURL: "http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local"
      s3Credentials:
        accessKeyId:
          name: ceph-rgw-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: ceph-rgw-s3-credentials
          key: ACCESS_SECRET_KEY
        region:
          name: ceph-rgw-s3-credentials
          key: ACCESS_REGION
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
  instances: 3
  storage:
    storageClass: ceph-block
    size: 10Gi
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/forgejo-db"
      endpointURL: "http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local"
      s3Credentials:
        accessKeyId:
          name: ceph-rgw-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: ceph-rgw-s3-credentials
          key: ACCESS_SECRET_KEY
        region:
          name: ceph-rgw-s3-credentials
          key: ACCESS_REGION
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-db
  namespace: infisical
spec:
  instances: 1
  storage:
    storageClass: ceph-block
    size: 10Gi
  bootstrap:
    initdb:
      database: infisical
      owner: infisical
      secret:
        name: infisical-db
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-db
  namespace: infisical
type: kubernetes.io/basic-auth
stringData:
  username: infisical
  password: ${INFISICAL_DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: ${INFISICAL_ENCRYPTION_KEY}
  AUTH_SECRET: ${INFISICAL_AUTH_SECRET}
  DB_CONNECTION_URI: "postgresql://infisical:${INFISICAL_DB_PASSWORD}@infisical-db-rw.infisical.svc.cluster.local:5432/infisical"
  REDIS_URL: ""
  SITE_URL: "https://infisical.quadtech.dev"
