# Do not edit this file manually.
# It was generated by nixos-generate-config and should be placed in:
# /etc/nixos/configuration.nix
# For manual customization, copy to hardware.nix and modify there.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE_WITH_UUID";
    fsType = "ext4";
  };

  swapDevices = [ ];

  powerManagement.cpuFreq governor = "performance";
}
