{
  config,
  pkgs,
  ...
}: {
  imports = [
    ../profiles/base.nix
    ../profiles/server.nix
    ../profiles/tailscale.nix
    ../profiles/docker.nix
    ../profiles/sops.nix
    ../profiles/kubernetes/control-plane.nix
    ../profiles/kubernetes/allow-master-workloads.nix
    ../profiles/kubernetes/kube-addons.nix
    ../services/helm-charts.nix
    ../services/argocd-apps.nix
    ../services/k8s-secrets-inject.nix
  ];

  environment.systemPackages = with pkgs; [
    git
    nfs-utils
    openiscsi
    openssl
    procps # For pkill command used by cloudflared scripts
  ];

  services.openiscsi = {
    enable = true;
    name = "iqn.2026-04.dev.quadtech:${config.networking.hostName}";
  };

  services.avahi = {
    enable = true;
    nssmdns4 = true;
    interfaces = ["enp0s31f6"];
    publish = {
      enable = true;
      addresses = true;
    };
  };

  services.resolved = {
    enable = true;
    settings.Resolve.MulticastDNS = "yes";
  };

  networking.firewall.allowedTCPPorts = [
    22
    443
    6443
    8888
  ];

  networking.hosts."192.168.1.240" = [
    "harbor.quadtech.dev"
  ];

  # sops.secrets are now auto-generated by machines/consumer.nix
  # via the typed-secrets library. Secrets are read from layered files:
  # secrets/shared.yaml → secrets/roles/backbone.yaml → secrets/hosts/backbone-01.yaml

  services.quadnix.argocdApps = {
    enable = true;
    harbor = true;
  };

  services.quadnix.k8s-secrets-inject = {
    enable = true;
  };

  # Forgejo Actions runners are managed in Kubernetes via forgejo-actions chart.

  # Cloudflared tunnel service (runs on host for SSH access via Cloudflare Tunnel)
  # Uses host IP 192.168.1.15 with NodePorts for K8s services
  systemd.services.cloudflared = {
    description = "Cloudflare Tunnel";
    wantedBy = ["multi-user.target"];
    wants = ["network.target"];
    after = ["network.target"];
    enable = true;
    serviceConfig = {
      ExecStart = "${pkgs.cloudflared}/bin/cloudflared tunnel --protocol http2 --config /etc/cloudflared/config/config.yaml run";
      Restart = "always";
      RestartSec = "5s";
      User = "root";
    };
    unitConfig = {
      StartLimitIntervalSec = "0";
    };
  };

  # Create cloudflared config directory and files
  systemd.services.cloudflared.preStart = ''
        mkdir -p /etc/cloudflared/config /etc/cloudflared/creds

        # Wait for the secret to be available
        for i in $(seq 1 30); do
          if [ -f /run/secrets/cloudflared-credentials ]; then
            break
          fi
          echo "Waiting for cloudflared credentials..."
          sleep 2
        done

        # Write cloudflared config - use 127.0.0.1 with NodePorts
        cat > /etc/cloudflared/config/config.yaml << 'EOF'
    ${builtins.toJSON (import ../../lib/cloudflared-config.nix {
      tunnelId = "b6bac523-be70-4625-8b67-fa78a9e1c7a5";
      credentialsFile = "/etc/cloudflared/creds/credentials.json";
    })}
    EOF

        # Copy credentials from SOPS secret
        cp /run/secrets/cloudflared-credentials /etc/cloudflared/creds/credentials.json
        chmod 600 /etc/cloudflared/creds/credentials.json
  '';

  # Host-based runners removed - runners now run on Kubernetes via forgejo-actions helm chart

  systemd.timers.git-pull = {
    description = "Pull git repo hourly";
    wantedBy = ["timers.target"];
    timerConfig = {
      OnCalendar = "hourly";
      Persistent = true;
    };
  };

  systemd.services.git-pull = {
    script = "cd /etc/nixos && ${pkgs.git}/bin/git pull";
    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };
}
