tunnel: b6bac523-be70-4625-8b67-fa78a9e1c7a5
credentials-file: /etc/cloudflared/creds/credentials.json
protocol: http2
metrics: 0.0.0.0:2002
no-autoupdate: true
ingress:
  - hostname: mainssh.voltrum.co
    service: ssh://localhost:22
  - hostname: forge-ssh.voltrum.co
    service: tcp://192.168.1.14:32222
  - hostname: forge.voltrum.co
    service: http://192.168.1.240:80
  - hostname: argocd.voltrum.co
    service: http://192.168.1.240:80
  - hostname: helpdesk.voltrum.co
    service: http://192.168.1.240:80
  - hostname: "api.orkestr-os.com"
    service: http://192.168.1.240:80
  - hostname: "*.voltrum.co"
    service: http://192.168.1.240:80
  - service: http_status:404
