{
  config,
  lib,
  ...
}: {
  sops = {
    defaultSopsFile = ../../secrets/${config.networking.hostName}.yaml;
    validateSopsFiles = true;
    age = {
      keyFile = "/etc/sops/age/keys.txt";
      generateKey = false;
    };
    # Individual secrets are now auto-generated by machines/consumer.nix
    # via the typed-secrets library. No manual sops.secrets entries needed here.
  };
}
