cloudflared-credentials: ENC[AES256_GCM,data:X4du1PwZwORJFJFDsK4v46iyQtCyYx5W2xBUABk2L2GjEbKaWHYI5JYNCj2bZlPM8mxEseLC7SQ9gLtQvkoXprwRVZOKS6JxW3wKT6KCJqv3fCpTPyvNEE2s7PkD2OWZsMnk4g6KjYAP+SC7U62RWoop9rf8+GbH+XDt76nniuQaIqEuBjmdt9N15jrTBjVxas/fcL7HjNiH61vR1i/jRfJln+La/W1F9zFz1H65ws0=,iv:9KZRLGb/CvcterW9hVtXYM0LPTNRajGqcL5buieOFg4=,tag:vflgcGdgfkEaWhVwaMDV8g==,type:str]
forgejo-db-password: ENC[AES256_GCM,data:4eG5p21+D2hYNROmHvbgecbCCEJ973ocNkhgOTbStH4=,iv:tkIodrCCiiQDl/L4v23qHdwoUcNthsOAoyXN5u/N2hA=,tag:i8hCUIMD+jGI9DCmEEfsIA==,type:str]
forgejo-admin-password: ENC[AES256_GCM,data:yXivbJB8o/IgeXOrsWxpkGQat8S5duF6LTewBfTwMmA=,iv:+vHdlxy0lrqL33W122IfzPbzvCGNVm+krm7NPMKeu1o=,tag:J6DjBJus9ETWVnY93JTT0A==,type:str]
forgejo-runner-token: ENC[AES256_GCM,data:plLMmmXBaw5pWwRQL2p8TOYrVc3t4B9Vylnw/PYiJ3vBTuyPKZBBaw==,iv:DgPfspjzLXGM9G9zo/rL6iASajm/CsTut/EdZ4nGwMQ=,tag:r9DQzoXV9EumwZReYFWCZQ==,type:str]
argocd-admin-password: ENC[AES256_GCM,data:JI2tjV9FObw5KMAtIXLfP0jF/nDWD2qj/X9LSnza/iLWsAqmgEuN1vDUGuFH/cuyBSJo0bINiOSMTpau,iv:fDbjexmz93i+LpzKlGBhdmJp2ISAgz+9BAnHEG5p+rA=,tag:sODQ5i0f039A9P/qqsf7TQ==,type:str]
argocd-forgejo-username: ENC[AES256_GCM,data:2Zox6RKJMjA=,iv:Vgj8KxS5wASd4kNEceJPChmRCVs1zwKij4i1BE0hWq8=,tag:Cv3Do4oycfUCvX8qj1et7w==,type:str]
argocd-forgejo-token: ENC[AES256_GCM,data:01rOHOxSkduMsTKhQ0NKhj9vs2GNZ2kTM09EG9o/BXX1jzOu1Hnacg==,iv:ymPUesLIH0BKHRE0e6OwFTCuTqaB3v0E4cqCmO8FD1Q=,tag:nfuUVIkNpBTHIOaS2/kgmQ==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
harbor-admin-password: ENC[AES256_GCM,data:H3bL8PTFF3q5cyk=,iv:uaTJd0fgDh+X9q+maVjWWAvGwxzDRjyzE/j5KcaZKkM=,tag:8ar+BVXR/SRDQQuk2hlfxw==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
harbor-registry-password: ENC[AES256_GCM,data:YqfaRMQ9goEExZK17IivGlQglCX9BN9w,iv:ULmjlvOMwiASUDNkftv+MaKWtl5Z4WSKArGLr5SgMX0=,tag:9uE4J+6mBclyK44EJcV01Q==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
cnpg-edukurs-password: ENC[AES256_GCM,data:ClB/MDLEvumkdPpPLG1r8Q==,iv:nopTo854i5nk+qrNGJrNNEh4F4RMmddylqM6sxewQos=,tag:iYIHyOzTuc25qk2knaZg5g==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
minecraft-rcon-password: ENC[AES256_GCM,data:TZe0FkpzvlYSW9CDOYifhbt6fbnYKyA=,iv:Sa4s9WLCe9Po69IqgWvEL6ktPNoKQUatSlY9yp2+pm4=,tag:4wqOh835osG+PDrRq5yORA==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
verdaccio-admin-password: ""
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
erpnext-db-admin-password: ENC[AES256_GCM,data:KJ+v4AlJ02yugg==,iv:2zmUsPavcQ/8lmEClq6AlVNhDkj8BCDTsW/i6gbwMhc=,tag:4rTP2yRHXonNTqzsfYGsPA==,type:str]
#ENC[AES256_GCM,data:qN1JeMV2tvwBJp1yvSD2nvzBu9nyd/KHsA==,iv:xUEjk8xWQc/y1cbVjpKfPbWjA5QobkSC2EIvKP7H0B4=,tag:2YM2u+k/o2lYM/UyIFQhcw==,type:comment]
erpnext-admin-password: ENC[AES256_GCM,data:+M7yanKKvew=,iv:e0oUiOEdliiwNvSSaCR04JMhkXslJBuSSh2EQs+FIR8=,tag:XUi0jySU8x93i9yWjIBVfg==,type:str]
openclaw-gateway-token: ENC[AES256_GCM,data:JNAT9XpKHxZfVNg47/RRtBGuwtV40fMuLYdcynrE31o=,iv:L2yWcS0W1MOQH2UYZ4oQTiaIKKv4cJFLgHAaRXXG4zw=,tag:cWYOMIz7uH447ASrfNl6CQ==,type:str]
openclaw-minimax-api-key: ENC[AES256_GCM,data:OF1GN+z3wAdHTrLaDbMS65fSyTWKX96YmsIWtKLwk27Am4mRpdcgI80BhGkUrDq62DvKAE+YuW1UqaxThla73QaFIVRn3Y/XYLGDflqgZtt2y0C8PE9IaZzxEEKeEU7hNlbmsNZ2WI7ZnmSokSNaILiS3o8+K+LrD3nAlPA=,iv:csonLlLZUFufMh/oMgnmu1JEL47YIs59ti8SsIU10j8=,tag:Y50hUg4n+92uHlYWHYepZQ==,type:str]
forgejo-agent-token: ENC[AES256_GCM,data:ja2xGLPGMIJ9mb4Y4/Bw3JmPjbTmhXsIVxJVX0EMC7AOasEphyCwnw==,iv:dK0YjJ1OhqfjQAk+EZMuBIhlVCd1uC0tjcohPW0UN2c=,tag:fkS93egf5VYsFzWbQ1PbDw==,type:str]
openclaw-discord-id: ENC[AES256_GCM,data:Y3Q/XersnCMHJr51vxvJ6WnEJjaFiCNNmoLyPtst0ZmwsTpX1FLbx9K9GF/Rz9WibG6uAxXrg8YSK00IXR3KtpXfgpBuxmoL,iv:QqSlYRV/8C0hkAA1ZXqqQ6ovGnpSE634Nwopm2yNl5w=,tag:18jvwX2LtgG0QQi/2j3DvQ==,type:str]
openclaw-server-id: ENC[AES256_GCM,data:4eHgJoio+KNww3AtYNx7HvgMqA==,iv:lPZDPn1JRkXKqahmaKRmdvFmyHsjACj567tQgvOMN7I=,tag:2xCxic5EG4aphUHD+iXtig==,type:int]
openclaw-beni-discord-id: ENC[AES256_GCM,data:C3OMG0S6bn7OgN1E36TPBC8a,iv:qnKbY+5FDRD5ZkSfUvrbwdGtDqhkxO40iFxWDxI4NuA=,tag:D0NnLhWFid1Y51k+lGIPLQ==,type:int]
grafana-admin-password: ENC[AES256_GCM,data:KC1Mgqq3aGQ0MEqC01k61MHAow==,iv:7Rqb6DJ/Q504Qfe7aZnf9WgrMA1oqvy6P/a3LngfH+4=,tag:51sobX8/S7vsD3NNSlfM7g==,type:str]
ceph-rgw-s3-access-key: ENC[AES256_GCM,data:3HzASgXmcXycqTauqNYWay/kxMo1/GlS,iv:2EVzdHMUOfKd51fGymRdZHKzmaaaIBdStq4V+J3wyII=,tag:PDuAO05kQ8ynBCGRnurHkQ==,type:str]
ceph-rgw-s3-secret-key: ENC[AES256_GCM,data:wrm1Na9mLtFCfaVZIh1ui229+yl28aMgS1/Q6yUO71kWwofHgmRv1Pfcf3z76gjt,iv:m4I4NvJJ9QRJ5bE9pNbaeEKvfjO3IpAxwzj/bqoPodE=,tag:5XFCZ1n0WM+JPcZVQCpSxA==,type:str]
quadpacienti-drilon-resend-key: ENC[AES256_GCM,data:YuV79oWE30mKKPy3H+a717B+oOvmXjDPSVaUeBIuGk0gUqWb,iv:70grIsLQsQJjumOeKqu42tj71ufqLNjG8UOZR+KuwuY=,tag:k3oJb6qIySQk/WmcJMOo6w==,type:str]
cloudflare-www-edit-workers-token: ENC[AES256_GCM,data:McUE8dT1dtnYvqhfsP1acMRPXDOJo4WWKbf9ZqtfScR2kACFlk7Td5WpnTXJAZyxGdKfvfA=,iv:JHuYZmHbn6ZrWHCR1L/5lNX4Tyl6mh2IAa630NnzUKw=,tag:UWgBh5FH//r7hLo9iOuAUA==,type:str]
orkestr-db-password: ENC[AES256_GCM,data:pMk7SSQgSaP4J2ly/fDX6eJsRhAB3zOlWRT+KYXq5Ik=,iv:8QdxlpUcu4pnS0xJafWcfPJskM/pGUsDRusmvuAYGEI=,tag:pqRMDGq8zz6+g2XvWFsaUg==,type:str]
orkestr-secret-key-base: ENC[AES256_GCM,data:Ud0Dmf1FyZM/EDSqqNFAA1/EZhkbuNCwB9fhymVjpSIXVHReytwH6dOXDULR3y12gRFZIQXKu0HutZDtELefC7T/Tpd857zzgHAqpWy2033yHi0Iq8lNj6SsSJoVltVy9TUcjp1MUMfiLXXjnlUz1d2DAGlgtace/gm6AjHE/gY=,iv:2VYq6w9UBgYYxNVBWF2AX72GV2fmjR2uUuk2Ct+2YzQ=,tag:QI/lqXmGarbIXpaNfW/AKA==,type:str]
orkestr-token-signing-secret: ENC[AES256_GCM,data:6ALGiG4IZAl050HsI99g1hanWeZfftNac9U2ptLDJ11Q+JxQARaa99E2Zl/ShUFNhd6jj4TpxW69rW46/BBJag==,iv:7YJSlDpfFadsAp6pvdFmBTs0eGnTvv3WZWFbPK3iR/k=,tag:CTE+880wcN0WLN0ltYPBUA==,type:str]
orkestr-electric-secret: ENC[AES256_GCM,data:I+LstWfmGvsE2uNB3P0YSZ4EhCQFb0TM5WIPrGCi6JOVVotKauplXBN4FUKmI9uR5YeoHzv7mhhhYgZoOPmrQQ==,iv:CG9Ro3FHy+8BciqeL0J55Pf+2UtoZvhwHO8u+/TCfRo=,tag:jaas1nGdiOUZrsVraIbozQ==,type:str]
orkestr-gemini-api-key: ENC[AES256_GCM,data:WIKEwoGGsfsPDuIAAcfKZgv0cqUC3snnqE25ZA1VZ4eyJnr2KEzE,iv:+HoK6hXfpNueu8MJXnnSCXp8ZUmuPBGD9V1ylggEN3M=,tag:dcWZxB2z68hx3zBB3y1xyw==,type:str]
wrangler-all-workers: ENC[AES256_GCM,data:XviH+5IoZ7XqNCjxVLrLxh5fBLNj9UOsGucJTlwgwhTbUboVM/GaW1jZZVevuHhx8eq5VoU=,iv:PiMY8fqfS6xgAWpB8b27tuCDI8Zklxrq/NsI1jz/P7k=,tag:9In5AK/ofZVpikJiPjkdFw==,type:str]
orkestr-resend-api-key: ENC[AES256_GCM,data:YETQBviU1IQchQcWgYD4T62RvpK1MbU=,iv:IPzwioUN+zq8kHwBREhnHUw0T6CHCA+TwQwFrbGjY6c=,tag:qBGSjjnY9iGG58cXTC7ZBA==,type:str]
librechat-zhipu-api-key: ENC[AES256_GCM,data:Rzq5fMOi45GETa4zFkTbAKncyofNIMENY6GR64UrNDSMam+EVxKKVh9yODRjE3fHqg==,iv:dl+RtQjTKdJXdiouJO0Pa3i0YaKommRyAN04oy9T714=,tag:weOMM49rTEVZeRvQt3QRcQ==,type:str]
librechat-minimax-api-key: ENC[AES256_GCM,data:U9s52X8EQyteFPaUwZy3+qC8u9WkHley3+0ymir/ofhCDTprSTb+z/y3lVNjBzVEoQmP6uOejeL9mJgL8dy2RYnwdh5ph21NyQEIQ6jqrrlSNaxvSDPYZ1sojftn9fQtxpnqu+nY5yCptD9dqq9WJWnToIBMgsfS+8RtL/8=,iv:sL1QGn1Bf5dvM01dGmK9SHJ7FZl6JwT+kbcisTyLzEU=,tag:YlN2s8FOUvHSJzrXdMKHIA==,type:str]
tailscale-auth-key: ENC[AES256_GCM,data:v2Yff/xUWnzrzA/mo7vKxDMRxu2paEPVyPl/lsRCF6YBTTYOfUoLGcuqDp5PRiBASfqpFwchb3XjHNPCyg==,iv:sXnQKn7+W7GHktf9GFC9t3GYAGq87IXRPABL59nxGEc=,tag:vnPv7etPCne5LSwa4X4Pag==,type:str]
librechat-jwt-secret: ENC[AES256_GCM,data:woNNSqMOCRU3Lbcj72dWvsk0tiiJXr+8A8qmQ7/ulckAYTkcllmAtw0xqYbmiiajYgfpcUOezHS7bG4TaK4hRg==,iv:PzacAZAoDIm69tywylRvm/iR3rwmOa8ZK5DfXxUpqHQ=,tag:JHwLdzvZgUONk9+ThegHFQ==,type:str]
orkestr-dns-cluster-query: ENC[AES256_GCM,data:YlFs40NyIX5dQNT7OxqPNovwu0rOmGjPp2U5bLw04oPjwTTDBMvPOiLJ,iv:0oK3E3H9WJYksNEL7KIHGpq522Lb53LequSyOMw9xlI=,tag:qUoOREB1LsThr/7TrbOtqw==,type:str]
sops:
    age:
        - recipient: age149k446qw7jhxszqs40y09a2n22um3056geunqm2mypg8e7dehgvsyn4ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWnhKY3dGWmFmL1d3Qy9p
            TnlvVkllYmNSZWRqRkxFYWQyQnFFekNqRlJZCmVkZGlidUJHelI0cnAwSHJLOEh3
            YWplb2tZcUFXbFRuR0s3T1IrbldNL28KLS0tIGZRYzFVdWRJYnZGSXY0aWdTRmlX
            UU1IYXdlYktTL2loSndDaEwrb0JIZXcKUlVNnldMFdtunkcb8Qyz7lsgSi37D5Gj
            e4/iaxlmvlKi46YQggRnUh5ylcMB4Nu+5r/QzEE6VLEv8eTYyPPX/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaEuHKb7PS/LyaBxvNzIcVzMOW0aDVHFnauM9pSjxm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtWM1YvUSBYUVAx
            TDJxMkFqVExvWjJoU0hyclZKQzFaZERKeUZEeHY4enJDTnB6TFRRCnpZd0pmYXNj
            K2FQRkxaQTRaUjFNcUlHWmNvSlNGb1ZHVmxnVWliOE5QakkKLS0tIHNMdTRQR2pG
            dzlqNjI1Y2ZyK0lxck45ekxDSys0SFB2RTNIa0NnRGJpUWsKW/TqLw8vGidAc8zV
            iGvvP9b7y4x9SBsspsKEdA2OjAYlcGabbaHIzUshjC+XPgjtjB6NmpSSSVbI/CMm
            Fudf8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQisXyPG28p3bjlL6slxTsZWdQRDBcIq0eKf388kjJk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhHSHRCZyBQeVFh
            Y2VwcFBUbDZPK3hWTTZxMVFRU3NkeS91azRQSUVjUDNjaWFvT1I4Ck4vK0duSWR4
            MnROMmRQaVh3TEQydFVVY1ZGOXZKTkpxTU1JTGhJbDU4ZUkKLS0tIEN1QTNoUWJI
            MnlZT2FEamovMVNuQ2REeFBCWTZhSG4xVjBQUTRya1BmeTAK0US/XataJvdpENtH
            goAEyMPYcBsaimaz65lKcb//W618CDS0zwzNzKeyQUaC6fEBPIIy6R9GU/1v0PVB
            XTrzOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDIjDVRgzc2UBRIbtwysmmW/F+zOjLm4PhmmKeYASoZK
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFI1TzBodyBvcmt3
            QWtvUXdpSUdvVUFjelliZTZnZGRzOUluY2JyNUxnTFNma0Zha3h3CmhITk85UzR6
            WWJyb1Bwbnc5U0tPd0pmNDdzRGNPNGR3T0ZpazlWSTNKd1UKLS0tIFp5OHlWQUpH
            QUVnVTFmOEp4VUJmSWtDTE5MRmkvWnpOQWViSzV6TWRHTmsKVqJ3KHbH4A2eWb4w
            04HEQj4vvkVW6Ee+JscIkzFQeY4n6YDleOTkc3FKUl+aqB6o+jxCn9m/g6f65RCM
            B6MQqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINxZcBLleNnJ8BXX7+3jA3xROZjlz3C5dM76VTsy/sLh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFmZW8wdyBLMGtK
            TlBWbEFSeGVQWExHN01pQS9Od1dqa3NBcC9ZWEVFbnZnR1orQ25JCldzbmdPMWQ0
            Sk5OKzJEanZ6eXZYQ1UwYjFWL1dvVnc2UmhnMTJHYnoxSTgKLS0tIFppRk40TDVl
            N044ejIyV0RwNGdKK0czY0xwdmxXVTBqSzlyZWhNUDRwbEUKtpRZoFkpClV5c8jv
            l/H00AjGlFLBg9/mxr/wY9D77PzLZNOEISxHmA9+bA3BmYjnuGuV4vDkgj0Hx/HY
            PigGjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T22:43:08Z"
    mac: ENC[AES256_GCM,data:5P3W6XP3LKN0CAsWjrpxHe+2curJ0nrhTDqiRA6KizKRW1fRk/EP6RceO8dI53Ah8w7zEobFhW8gtdyKhMzag+R/1K8ZHe0DMFlV8xa0X+AtNN3huUIg6o4JI11OEnCdttlEy8gapVv84OZ/jr7MH3eeG+NpcAJdZ/4FjS228io=,iv:8+yzDYfXbvCTSx0er476WR8vO4bEb+18hdsVrF1yrQY=,tag:zxOxRPefoecp+5AG++VE7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
